name: ðŸ”— md-padding è‡ªåŠ¨åŠ ç©ºæ ¼

on: 
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    name: md-padding
    runs-on: ubuntu-latest
    
    steps:
        - name: Checkout from repository
          uses: actions/checkout@v4
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: '20'
          
        - name: Install Node.js dependencies 
          run: npm i -g  --no-fund md-padding && npx mdp --version
        
        - name: Run md-padding to add spaces
          run: find "$(pwd)" -type f -name "*.md" | npx md-padding --ignore-words='-' '=' ':' '>' '<' 'â†’' '"ï¼‰' '[â€¦]' '[' 'ï¼ˆ1"ï¼‰' ']' '!' ',' -f --read-files -i

        - name: PR Changes by md-padding
          uses: peter-evans/create-pull-request@v6
          with:
             commit-message: "Markdown add spaces"
             labels: "Markdown"
             delete-branch: true
             title: Markdown add spaces
             body: æ ¼å¼åŒ–â€”â€”ä½¿ç”¨ md-padding ç»™ Markdown è‡ªåŠ¨åŠ ç©ºæ ¼
