name: Push changes to Handbook-Next

on:
  push:
    branches: [main]

jobs:
  build:
    name: Push changes to Handbook-Next
    runs-on: ubuntu-latest

    steps:
      - name: Checkout from repository
        uses: actions/checkout@v3.0.2

      - name: Push changes to Handbook-Next
        uses: dmnemec/copy_file_to_another_repo_action@v1.1.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}

        with:
          source_file: "."
          destination_repo: "FreeBSD-Ask/Handbook-Next"
          destination_folder: "docs"
          user_name: "${{ github.event.pusher.name }}"
          user_email: "${{ github.event.pusher.email }}"
